--全局modifier初始化
LinkLuaModifier( "modifier_critical_strike","items/modifier_items/modifier_critical_strike", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_blue_bottle_small","items/modifier_items/modifier_item_blue_bottle_small", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_blue_bottle_large","items/modifier_items/modifier_item_blue_bottle_large", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_red_bottle_large","items/modifier_items/modifier_item_red_bottle_large", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_red_bottle_small","items/modifier_items/modifier_item_red_bottle_small", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_custom_rune_haste02","items/modifier_items/modifier_item_custom_rune_haste02", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hero_bead_buff","items/modifier_items/modifier_hero_bead_buff", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hero_add_health","items/modifier_items/modifier_hero_add_health", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_rune_double","items/modifier_items/modifier_item_rune_double", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_rune_magice","items/modifier_items/modifier_item_rune_magice", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_rune_yinshen","items/modifier_items/modifier_item_rune_yinshen", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_movespeed_cap","items/modifier_items/modifier_movespeed_cap", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sword_damage","items/modifier_items/modifier_sword_damage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_currier","items/modifier_items/modifier_currier", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_custom_wudi","items/modifier_items/modifier_custom_wudi", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_burn_lua","items/modifier_items/modifier_burn_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_rune_illusions","items/modifier_items/modifier_item_rune_illusions", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_item_rune_speed","items/modifier_items/modifier_item_rune_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_currier_pickup_item","items/modifier_items/modifier_currier_pickup_item", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_currier_send_item","items/modifier_items/modifier_currier_send_item", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_test","items/modifier_items/modifier_test", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_temporary_property","items/modifier_items/modifier_temporary_property", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_kill_self","items/modifier_items/modifier_kill_self", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_kill_self_count","items/modifier_items/modifier_kill_self", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_kill_self_rooted","items/modifier_items/modifier_kill_self", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_custom_xuanyun","items/modifier_items/modifier_custom_xuanyun", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shangren","items/modifier_items/modifier_shangren", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_cast_ability","items/modifier_items/modifier_cast_ability", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_fangyu_jihuo_add","ability/abilities_lua/modifier/modifier_fangyu_jihuo_add", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shouren_didong","ability/abilities_lua/modifier/modifier_shouren_didong", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shouren_didong_no_see","ability/abilities_lua/modifier/modifier_shouren_didong", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_jiaoxie","ability/abilities_lua/modifier/modifier_shouren_didong", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "modifier_vip_show_buff_lua","ability/abilities_lua/modifier/modifier_vip_show_buff_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_show_box_lua","ability/abilities_lua/modifier/modifier_vip_show_buff_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_get_exp_lua","ability/abilities_lua/modifier/modifier_get_exp_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_create_hero_lua","ability/abilities_lua/modifier/modifier_create_hero_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_attack_speed_lua","ability/abilities_lua/modifier/modifier_attack_speed_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_agility_gain_lua","ability/abilities_lua/modifier/modifier_agility_gain_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_intellect_gain_lua","ability/abilities_lua/modifier/modifier_intellect_gain_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_strength_gain_lua","ability/abilities_lua/modifier/modifier_strength_gain_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_heath_hp_lua","ability/abilities_lua/modifier/modifier_heath_hp_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_damage_percent_lua","ability/abilities_lua/modifier/modifier_damage_percent_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_physical_armor_lua","ability/abilities_lua/modifier/modifier_physical_armor_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_extra_strength_lua","ability/abilities_lua/modifier/modifier_extra_strength_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_paralyzed","ability/abilities_lua/modifier/modifier_paralyzed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_imba_stunned","ability/abilities_lua/modifier/modifier_imba_stunned", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_left_hand","ability/abilities_lua/modifier/modifier_gem_god_left_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_right_hand","ability/abilities_lua/modifier/modifier_gem_god_right_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_hand","ability/abilities_lua/modifier/modifier_gem_god_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_bow_of_aeolus","ability/abilities_lua/modifier/modifier_gem_bow_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_arrow_of_aeolus","ability/abilities_lua/modifier/modifier_gem_arrow_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_power_of_aeolus","ability/abilities_lua/modifier/modifier_gem_power_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_right_wristbands","ability/abilities_lua/modifier/modifier_gem_blacksmith_right_wristbands", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_left_wristbands","ability/abilities_lua/modifier/modifier_gem_blacksmith_left_wristbands", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_power","ability/abilities_lua/modifier/modifier_gem_blacksmith_power", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shuangren_fu","ability/abilities_lua/modifier/modifier_gem_shuangren_fu", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_zheng_zhong_ba_xin","ability/abilities_lua/modifier/modifier_zheng_zhong_ba_xin", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_yu_zhan_yu_yong","ability/abilities_lua/modifier/modifier_yu_zhan_yu_yong", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_chougou","ability/abilities_lua/modifier/modifier_chougou", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_chougou_damage","ability/abilities_lua/modifier/modifier_chougou", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_silenced_lua","ability/abilities_lua/modifier/modifier_silenced_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shebang","ability/abilities_lua/modifier/modifier_shebang", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_diyuhuo","ability/abilities_lua/modifier/modifier_diyuhuo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_huojiandan","ability/abilities_lua/modifier/modifier_huojiandan", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_huojiandan_qianghuang","ability/abilities_lua/modifier/modifier_huojiandan", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_change_penhuo_point","ability/abilities_lua/modifier/modifier_change_penhuo_point", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_passive_lightning_chain_unit_thinker","ability/abilities_lua/modifier/modifier_passive_lightning_chain_unit_thinker", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_change_penhuo_damage","ability/abilities_lua/modifier/modifier_change_penhuo_damage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sanweizhenhuo","ability/abilities_lua/modifier/modifier_sanweizhenhuo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sanweizhenhuo_damage","ability/abilities_lua/modifier/modifier_sanweizhenhuo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sanweizhenhuo_hit_point","ability/abilities_lua/modifier/modifier_sanweizhenhuo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_huodun","ability/abilities_lua/modifier/modifier_huodun", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_zhi_yuan_xiao_pao","ability/abilities_lua/modifier/modifier_zhi_yuan_xiao_pao", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_active_jinjicheli","ability/abilities_lua/modifier/modifier_active_jinjicheli", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier( "modifier_yinhangshengzhuanggouzi_intell","ability/abilities_lua/modifier/modifier_yinhangshengzhuanggouzi_add", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_yinhangshengzhuanggouzi_strength","ability/abilities_lua/modifier/modifier_yinhangshengzhuanggouzi_add", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_yinhangshengzhuanggouzi_agility","ability/abilities_lua/modifier/modifier_yinhangshengzhuanggouzi_add", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_mechanical_modification_add","ability/abilities_lua/modifier/modifier_mechanical_modification_add", LUA_MODIFIER_MOTION_NONE )

--modifier_unit
LinkLuaModifier( "modifier_xiaozhuzai","ability/abilities_lua/modifier_unit/modifier_xiaozhuzai", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_overgrowth","ability/abilities_lua/modifier_unit/modifier_wood_overgrowth", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_overgrowth_damage","ability/abilities_lua/modifier_unit/modifier_wood_overgrowth", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_call_settlement","ability/abilities_lua/modifier_unit/modifier_wood_call_settlement", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_call_dominated","ability/abilities_lua/modifier_unit/modifier_wood_call_settlement", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_call_attack_by_friendly","ability/abilities_lua/modifier_unit/modifier_wood_call_settlement", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_tuji","ability/abilities_lua/modifier_unit/modifier_wood_tuji", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier( "modifier_wood_tuji_damage","ability/abilities_lua/modifier_unit/modifier_wood_tuji", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_tuji_damage_mark","ability/abilities_lua/modifier_unit/modifier_wood_tuji", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_fenshen","ability/abilities_lua/modifier_unit/modifier_wood_fenshen", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wood_fenshen_check","ability/abilities_lua/modifier_unit/modifier_wood_fenshen", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_rangesound_lua","ability/abilities_lua/modifier_unit/modifier_rangesound_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_meleesound_lua","ability/abilities_lua/modifier_unit/modifier_meleesound_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_physics_piercing_lua","ability/abilities_lua/modifier_unit/modifier_physics_piercing_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_backround_music","ability/abilities_lua/modifier_unit/modifier_backround_music", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_damage_up","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_damage_up_do","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_attackspeed","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_attackspeed_do","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_armor","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_armor_do","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_ability","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_state_aura_ability_do","ability/abilities_lua/modifier_unit/modifier_state_aura", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_attribute_50_lua","ability/abilities_lua/modifier_unit/modifier_attribute_50_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_clear_space","ability/abilities_lua/modifier_unit/modifier_clear_space", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "modifier_addgold_second_lua","ability/abilities_lua/modifier_unit/modifier_addgold_second_lua", LUA_MODIFIER_MOTION_NONE )


LinkLuaModifier( "modifier_tower_repair_1","tower/tower_system", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_tower_repair_2","tower/tower_system", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_extra_attack_scale_lua","ability/abilities_lua/modifier/modifier_extra_attack_scale_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_show_properties_lua","ability/abilities_lua/modifier_unit/modifier_show_properties_lua", LUA_MODIFIER_MOTION_NONE )

-- 投资属性
LinkLuaModifier( "modifier_lueduo_lua","ability/economics_lua/modifier_lueduo_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_maoyi_lua","ability/economics_lua/modifier_maoyi_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_shalu_lua","ability/economics_lua/modifier_shalu_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_touzi_lua","ability/economics_lua/modifier_touzi_lua", LUA_MODIFIER_MOTION_NONE )

-- 词缀
LinkLuaModifier( "modifier_prefix_amon_lua","ability/abilities_lua/modifier_fix/modifier_prefix_amon_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_prefix_anubis_lua","ability/abilities_lua/modifier_fix/modifier_prefix_anubis_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_prefix_ra_lua","ability/abilities_lua/modifier_fix/modifier_prefix_ra_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_prefix_horus_lua","ability/abilities_lua/modifier_fix/modifier_prefix_horus_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_prefix_osiris_lua","ability/abilities_lua/modifier_fix/modifier_prefix_osiris_lua", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "modifier_suffix_desert_lua","ability/abilities_lua/modifier_fix/modifier_suffix_desert_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_suffix_earth_lua","ability/abilities_lua/modifier_fix/modifier_suffix_earth_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_suffix_forest_lua","ability/abilities_lua/modifier_fix/modifier_suffix_forest_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_suffix_sky_lua","ability/abilities_lua/modifier_fix/modifier_suffix_sky_lua", LUA_MODIFIER_MOTION_NONE )

-- 通用
LinkLuaModifier( "modifier_common_stun","ability/abilities_lua/modifier/modifier_common_stun", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_conmon_boss","ability/abilities_lua/modifier/modifier_conmon_boss", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_common_move_speed","ability/abilities_lua/modifier/modifier_common_move_speed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_common_tp","ability/abilities_lua/modifier/modifier_common_tp", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_common_knockback","ability/abilities_lua/modifier/modifier_common_knockback", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier( "modifier_common_attack_speed","ability/abilities_lua/modifier/modifier_common_attack_speed", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier( "modifier_common_physical_armor","ability/abilities_lua/modifier/modifier_common_physical_armor", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier( "modifier_base_get_gold","ability/abilities_lua/modifier/modifier_base_get_gold", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_test","ability/abilities_lua/modifier/modifier_test", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_killing_heart","ability/abilities_lua/modifier/modifier_killing_heart", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_common_no_health_bar","ability/abilities_lua/modifier/modifier_common_no_health_bar", LUA_MODIFIER_MOTION_NONE )
