-- 精英光环随机池
return {
    "aura_increase_physical_armor",
    "aura_decrease_physical_armor",
    "aura_increase_attack_damage",
    "aura_decrease_attack_damage",
    "aura_increase_attack_speed",
    "aura_decrease_attack_speed",
    "aura_increase_move_speed",
    "aura_decrease_move_speed",
    "aura_increase_magical_resistance",
    "aura_decrease_magical_resistance",
    "aure_drain_mana",
    "aure_dark_night",
    "aure_heat",
    "aure_shield_wall",
    "aure_avoid_spell",
    "aure_heal_hp",
    "aure_pure_damage",
}