-- config_random_ability.lua 随机技能池
-- mobnumber = 10

return {
    -- 波次配置
    ["d"] = {
        -- 品质
        ["quality"] = "D",
        -- 主动技能随机池
        ["activepool"] = {
            "tg_jk_db_d",
            "imba_pugna_nether_blast_d",
            "imba_omniknight_purification_d",
            "starfall_lua_d",
            "imba_centaur_hoof_stomp_d",
            "call_shebang_d",
            "call_diyuhuo_d",
            "active_wind_array_arrow_d",
            "call_huojian_d",
            "active_tornado_lua_d",
            "initiative_siphon_lua_d",
            "initiative_poison_circle_lua_d",  
            "initiative_sword_gold_lua_d",
            "initiative_lichang_lua_d",
            "initiative_fire_support_lua_d",
            "initiative_cross_lua_d",
            "initiative_bullet_fly_lua_d",
            "initiative_sickle_lua_d",
            "initiative_hit_jump_lua_d",
            "initiative_jixingjianqi_lua_d",
            "ice_boom_d",
            "fluctuating_chopping_d",
            "ray_d",
            -- "imba_crystal_maiden_freezing_field_b",
        },
        -- 被动动技能随机池
        ["passivepool"] = {
            "dragon_knight_dragon_blood_d",
            "phantom_assassin_blur_d",
            "passive_changbiyuan_lua_d",
            "passive_addall_attribute_lua_d",
            "passive_add_crit_lua_d",
            "passive_toxicity_of_the_skin_lua_d",
            "passive_vampire_lua_d",
            "passive_kongju_haojiao_lua_d",
            "passive_jingji_pifu_lua_d",
            "passive_fumo_weapon_lua_d",
            "passive_aoshu_mingxiang_lua_d",
            "passive_turbulence_magic_lua_d",
            "passive_mingyun_gutou_lua_d",
            "passive_qiaqi_coming_lua_d",
            "passive_zhenwu_zhenfa_lua_d",
            "passive_berserker_lua_d",
            "passive_pillage_lua_e",
            "whirlwind_d",
        },
    },
    ["c"] = {
        -- 品质
        ["quality"] = "C",
        -- 主动技能随机池
        ["activepool"] = {
            "tg_jk_db_c",
            "imba_pugna_nether_blast_c",
            "imba_omniknight_purification_c",
            "starfall_lua_c",
            "imba_centaur_hoof_stomp_c",
            "call_shebang_c",
            "call_diyuhuo_c",
            "active_wind_array_arrow_c",
            "call_huojian_c",
            "call_tianshi_c",
            "initiative_siphon_lua_c",
            "initiative_poison_circle_lua_c",
            "initiative_sword_gold_lua_c",
            "initiative_lichang_lua_c",
            "initiative_cross_lua_c",
            "initiative_bullet_fly_lua_c",
            "initiative_sickle_lua_c",
            "initiative_jixingjianqi_lua_c",
            "initiative_hit_jump_lua_c",
            "ice_boom_c",
            "fluctuating_chopping_c",
            "ray_c",
            "initiative_fire_support_lua_c",
        },
        -- 被动动技能随机池
        ["passivepool"] = {
            "sven_great_cleave_c",
            "dragon_knight_dragon_blood_c",
            "phantom_assassin_blur_c",
            "faceless_void_time_lock_c",
            "shredder_reactive_armor_c",
            "luna_moon_glaive_c",
            "kunkka_tidebringer_c",
            "passive_changbiyuan_lua_c",
            "passive_addall_attribute_lua_c",
            "passive_lightning_chain_lua_c",
            "passive_add_crit_lua_c",
            "passive_toxicity_of_the_skin_lua_c",
            "passive_vampire_lua_c",
            "passive_kongju_haojiao_lua_c",
            "passive_shibao_lua_c",
            "passive_jingji_pifu_lua_c",
            "passive_fumo_weapon_lua_c",
            "passive_aoshu_mingxiang_lua_c",
            "passive_turbulence_magic_lua_c",
            "passive_mingyun_gutou_lua_c",
            "passive_qiaqi_coming_lua_c",
            "passive_zhenwu_zhenfa_lua_c",
            "passive_berserker_lua_c",
            "passive_pillage_lua_d",
            "whirlwind_c",
        },
    },
    ["b"] = {
        -- 品质
        ["quality"] = "B",
        -- 主动技能随机池
        ["activepool"] = {
            "tg_jk_db_b",
            -- "imba_earthshaker_echo_slam",
            "tg_lh_de_b",
            "imba_crystal_maiden_freezing_field_b",
            -- "imba_disruptor_thunder_strike_b",
            -- "imba_troll_warlord_whirling_axes_ranged_b",
            "call_shebang_b",
            "active_wind_array_arrow_b",
            "initiative_cross_lua_b",
            "initiative_bullet_fly_lua_b",
            -- "initiative_space_broken_lua_b",
            -- "laser_turret_b",
            "earth_fission_b",
            "photon_wall_b",
            "tow_ball_b",
            "call_daniu_b",
        },
        -- 被动动技能随机池
        ["passivepool"] = {
            "sven_great_cleave_b",
            "dragon_knight_dragon_blood_b",
            "phantom_assassin_blur_b",
            "faceless_void_time_lock_b",
            "shredder_reactive_armor_b",
            "luna_moon_glaive_b",
            "kunkka_tidebringer_b",
            "imba_faceless_void_time_lock_b",
            "passive_changbiyuan_lua_b",
            "passive_addall_attribute_lua_b",
            "passive_lightning_chain_lua_b",
            "passive_add_crit_lua_b",
            "passive_toxicity_of_the_skin_lua_b",
            "passive_vampire_lua_b",
            "passive_kongju_haojiao_lua_b",
            "passive_shibao_lua_b",
            "passive_jingji_pifu_lua_b",
            "passive_fumo_weapon_lua_b",
            "passive_aoshu_mingxiang_lua_b",
            "passive_gasify_lua_b",
            "passive_turbulence_magic_lua_b",
            "passive_mingyun_gutou_lua_b",
            "passive_qiaqi_coming_lua_b",
            "passive_zhenwu_zhenfa_lua_b",
            "passive_pillage_lua_c",
            "cold_ice_b",
        },
    },
    ["a"] = {
        -- 品质
        ["quality"] = "A",
        -- 主动技能随机池
        ["activepool"] = {
            "tg_jk_db_a",
            "tg_lh_de_a",
            "imba_crystal_maiden_freezing_field_a",
            -- "imba_disruptor_thunder_strike_a",
            -- "imba_gyrocopter_helicopter_form_a",
            -- "imba_troll_warlord_whirling_axes_ranged_a",
            "call_shebang_a",
            "active_wind_array_arrow_a",
            "active_big_jump_lua_a",
            "initiative_cross_lua_a",
            "initiative_bullet_fly_lua_a",
            -- "initiative_space_broken_lua_a",
            "laser_turret_a",
            "tow_ball_a",
            "earth_fission_a",
            "photon_wall_a",
        },
        -- 被动动技能随机池
        ["passivepool"] = {
            "sven_great_cleave_a",
            "dragon_knight_dragon_blood_a",
            "phantom_assassin_blur_a",
            "faceless_void_time_lock_a",
            "shredder_reactive_armor_a",
            "luna_moon_glaive_a",
            "kunkka_tidebringer_a",
            "imba_faceless_void_time_lock_a",
            "passive_changbiyuan_lua_a",
            "passive_addall_attribute_lua_a",
            "passive_lightning_chain_lua_a",
            "passive_toxicity_of_the_skin_lua_a",
            "passive_vampire_lua_a",
            "passive_shibao_lua_a",
            "passive_aoshu_mingxiang_lua_a",
            "passive_gasify_lua_a",
            "passive_turbulence_magic_lua_a",
            "passive_mingyun_gutou_lua_a",
            "passive_qiaqi_coming_lua_a",
            "passive_zhenwu_zhenfa_lua_a",
            -- "passive_shock_lua_a",
            "passive_pillage_lua_b",
            "cold_ice_a"
        },
    },
    ["s"] = {
        -- 品质
        ["quality"] = "S",
        -- 主动技能随机池
        ["activepool"] = {
            "tg_jk_db_s",
            "tg_lh_de_s",
            -- "imba_gyrocopter_helicopter_form_s",
            "active_wind_array_arrow_s",       
            "active_big_jump_lua_s",
            "initiative_cross_lua_s",
            "initiative_bullet_fly_lua_s",
            "explosion_lightning_s",
            "laser_turret_s",
        },
        -- 被动动技能随机池
        ["passivepool"] = {
            "skeleton_king_reincarnation_s",
            "phantom_assassin_blur_s",
            "faceless_void_time_lock_s",
            "shredder_reactive_armor_s",
            "luna_moon_glaive_s",
            "kunkka_tidebringer_s",
            "imba_faceless_void_time_lock_s",
            "imba_troll_warlord_fervor_s",
            "passive_addall_attribute_lua_s",
            "passive_vampire_lua_s",
            "passive_gasify_lua_s",
            "passive_turbulence_magic_lua_s",
            "passive_mingyun_gutou_lua_s",
            "passive_qiaqi_coming_lua_s",
            "passive_zhenwu_zhenfa_lua_s",
            "passive_shock_lua_s",
        },
    },
}